- name: add jenkins repo key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

- name: add jenkins repo
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'

- name: install jenkins
  apt: name=jenkins state=latest

- name: add /etc/sudoers.d/10-jenkins
  copy: src=etc/sudoers.d/10-jenkins dest=/etc/sudoers.d/10-jenkins owner=root group=root mode=0440

- name: enable jenkins service
  service: name=jenkins enabled=yes
