- name: add redis repo
  apt_repository: repo=ppa:chris-lea/redis-server

- name: install redis
  apt: name=redis-server

- name: update /etc/redis/redis.conf
  copy: src=etc/redis/redis.conf dest=/etc/redis/redis.conf
  notify: restart-redis

- name: enable redis service
  service: name=redis-server enabled=yes
