- name: add rabbitmq repo key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc

- name: add rabbitmq repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main'

- name: install rabbitmq
  apt: name=rabbitmq-server

- name: update rabbitmq service
  service: name=rabbitmq-server state=restarted enabled=yes

- name: create rabbitmq user
  rabbitmq_user: user={{rabbitmq_user}} password={{rabbitmq_password}} configure_priv=.* read_priv=.* write_priv=.* state=present
  when: rabbitmq_user != ""
