- name: add elasticsearch repo key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: add elasticsearch repo
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main'

- name: install elasticsearch
  apt: name=elasticsearch

- name: update /etc/elasticsearch/elasticsearch.yml
  template: src=etc/elasticsearch/elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart-elasticsearch

- name: update elasticsearch service
  service: name=elasticsearch enabled=yes
