- name: install mysql
  apt: name=mysql-server-5.6
  register: mysql_installed

- name: create mysql admin user
  command: /usr/bin/mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO {{mysql_admin_user}}@'%' IDENTIFIED BY '{{mysql_admin_password}}';"
  when: mysql_installed.changed

- name: update /etc/mysql/conf.d/bind.cnf
  copy: src=etc/mysql/conf.d/bind.cnf dest=/etc/mysql/conf.d/bind.cnf
  notify: restart-mysql

- name: enable mysql service
  service: name=mysql enabled=yes

