- name: uninstall openjdk
  apt: name=openjdk state=absent purge=true

- name: add ppa:webupd8team/java
  apt_repository: repo='ppa:webupd8team/java'

- name: accept oracle license
  debconf: name='oracle-java{{jdk_version}}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install jdk
  apt: name=oracle-java{{jdk_version}}-installer

- name: set jdk as default
  apt: name=oracle-java{{jdk_version}}-set-default

- name: update JCE jar
  copy: src=security/ dest=/usr/lib/jvm/java-{{jdk_version}}-oracle/jre/lib/security owner=root group=root mode=0644