- name: add mongodb repo key
  apt_key: id=7F0CEB10 keyserver=hkp://keyserver.ubuntu.com:80

- name: add mongodb repo
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'

- name: install mongodb
  apt: name=mongodb-org

- name: update /etc/mongod.conf
  copy: src=etc/mongod.conf dest=/etc/mongod.conf

- name: update mongodb service
  service: name=mongod state=restarted enabled=yes
