- name: add mongodb repo key
  apt_key: id=7F0CEB10 keyserver=hkp://keyserver.ubuntu.com:80

- name: add mongodb repo
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse'

- name: install mongodb
  apt: name=mongodb-org

- name: update /etc/mongod.conf
  copy: src=etc/mongod.conf dest=/etc/mongod.conf
  notify: restart-mongodb

- name: enable mongodb service
  service: name=mongod enabled=yes
