- name: create /opt/ec2
  file: path=/opt/ec2 owner=root group=root state=directory

- name: install pip
  apt: name=python-pip

- name: install awscli/boto
  pip: name={{item}}
  with_items: [awscli, boto]

- include: s3-upload-log.yml
  when: ec2_log_s3_bucket != ""

- include: cloudwatch-linux.yml
  when: '"linux" in ec2_cloudwatch_metrics'

- include: cloudwatch-java.yml
  when: '"java" in ec2_cloudwatch_metrics'