- name: install pip
  apt: name=python-pip

- name: install awscli
  pip: name=awscli

- name: update /etc/cron.hourly/20-logrotate-upload-to-s3
  template: src=etc/cron.hourly/20-logrotate-upload-to-s3.j2 dest=/etc/cron.hourly/20-logrotate-upload-to-s3 owner=root group=root mode=0755

- name: update /opt/env/shutdown.sh
  copy: src=opt/env/shutdown.sh dest=/opt/env/shutdown.sh owner=root group=root mode=0755

- name: add shutdown hook
  copy: src=etc/sysctl.d/10-logrotate-shutdown-hook.conf dest=/etc/sysctl.d/10-logrotate-shutdown-hook.conf owner=root group=root mode=0644