- name: add nginx repo
  apt_repository: repo=ppa:nginx/stable

- name: install nginx
  apt: name=nginx

- name: update /etc/nginx/*
  copy: src=etc/nginx/ dest=/etc/nginx owner=root group=root mode=0644
  notify: restart-nginx

- name: update /etc/nginx/sites-available/default
  template: src=etc/nginx/sites-available/default.j2 dest=/etc/nginx/sites-available/default owner=root group=root mode=0644
  notify: restart-nginx

- name: update /etc/nginx/sites-enabled/default
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default state=link
  notify: restart-nginx

- name: create /var/www
  file: path=/var/www owner=www-data group=adm mode=0775 state=directory

- name: add ubuntu to adm group for deployment
  user: name=ubuntu groups=adm append=yes

- name: create /opt/log/nginx
  file: path=/opt/log/nginx owner=www-data group=adm mode=0755 state=directory

- name: update /etc/logrotate.d/nginx
  copy: src=etc/logrotate.d/nginx dest=/etc/logrotate.d/nginx

- name: enable nginx service
  service: name=nginx enabled=yes