- hosts: localhost
  roles: [sys, supervisor, jdk, redis]
  vars:
    supervisor_programs:
      demo:
        command: '/opt/app/demo-service-3.0.0/bin/demo-service'
        env: 'JAVA_OPTS="-XX:+UseG1GC"'

  tasks:
    - name: disable puppet
      service: name=puppet enabled=no state=stopped
    - name: disable chef
      service: name=chef-client enabled=no state=stopped