- hosts: localhost
  roles: [sys, jdk, nginx, tomcat, logrotate]
  vars:

  tasks:
    - name: disable puppet
      service: name=puppet enabled=no state=stopped
    - name: disable chef
      service: name=chef-client enabled=no state=stopped